### ISSUE TITLE
Support variable height for the rotation handle line

### ISSUE THREAD

**Issue by wassgha** [daybrush/moveable#167]
## Description
In addition to `rotationPosition`, it would be great if there was support for `rotationHeight` that defines how far the rotation handle is from the object. Currently this is hardcoded to `40px` and there is no way to override it in CSS since it requires overriding the `transform` attributes (which also rotates and translates the rotation handle line).

**Comment by daybrush** [comment]
@wassgha 

Moveable 0.14.0 is released. Thank you :)

Changed to top instead of transform
```css
.rCS4nn8ek .moveable-line.moveable-rotation-line{
	height: 40px;
	width: 1px;
    transform-origin: 0.5px 39.5px;
    top: -40px;
}
```

* `moveable` 0.14.0
* `react-moveable` 0.17.0
* `preact-moveable` 0.16.0
* `ngx-moveable` 0.10.0
* `svelte-moveable` 0.5.0
