### ISSUE TITLE
how to hide snap distance 

### ISSUE THREAD

**Issue by hangzz** [daybrush/moveable#186]
## Environments
* Framework name: moveable
* Framework version:  0.14.1

## Description

i need snap, but i want to hide snap distance

**Comment by daybrush** [comment]
@hangzz 

The option will be added in a future release. For now, the only way to get rid of it is with CSS.

```css
.moveable-line.moveable-dashed:before {
    position: absolute;
    content: attr(data-size);
    color: #4af;
    font-size: 12px;
    font-weight: bold;
}
```
