### ISSUE TITLE
how to change color of guildelines

### ISSUE THREAD

**Issue by zc9** [daybrush/moveable#469]
how to change color of guildelines

**Comment by ccpu** [comment]
This project has been structured well, look into the files should give you lots of info,
[here is how snappable has been styled](https://github.com/daybrush/moveable/blob/306d221577c4f093c6d020f516bccc83e733383f/packages/react-moveable/src/react-moveable/ables/Snappable.tsx#L1631).

so this should do:

```css
  .moveable-bold,
  .moveable-target,
  .moveable-vertical {
    background-color: green !important;
  }

  .moveable-dashed {
    border-color: green !important;
  }
```
