### ISSUE TITLE
How to hide the outer border

### ISSUE THREAD

**Issue by topdevelop** [daybrush/moveable#547]
I set the origin property, but it doesn't seem to work

**Comment by daybrush** [comment]
@topdevelop 

Handle the child element of moveable with css.

**Comment by aayush801** [comment]
> @topdevelop
> 
> Handle the child element of moveable with css.

How exactly do I do this ?

**Comment by daybrush** [comment]
@aayush801 

```css

.moveable-control.moveable-origin {
	border-color: #f55;
	background: #fff;
	width: 12px;
	height: 12px;
	margin-top: -6px;
        margin-left: -6px;
	pointer-events: none;
}
```
