### ISSUE TITLE
Retrieve the generated snap line when "snap" event is triggered

### ISSUE THREAD

**Issue by alexconstantin** [daybrush/moveable#707]
## Environments
* Framework name: Vanilla
* Framework version: -
* Moveable Component version: 0.32.0
* Testable Address(optional): -

## Description
Hello, I was playing around with the .on("snap") event and I saw that we receive arrays for gaps, elements, guidelines, which is pretty cool! I was wondering if there was a way to also receive the generated moveable-line div in that event (through a unique class name or the actual html element). The reason for this is that, for purely UI/UX considerations, I would want to color some lines differently. I am achieving this at the moment by using a MutationObserver object on the control-box div and I am searching for lines with a certain width / height. This works as expected, but I think this is poor from performance POV. 

Would this functionality be achievable or is there another way of obtaining the same result without using the MutationObserver API? 

Thank you!

![Screenshot 2022-07-24 at 15 00 25](https://user-images.githubusercontent.com/6921332/180646004-eaccf28a-5f49-457b-96d8-a727dd227207.png)

**Comment by daybrush** [comment]
@alexconstantin 


* `lit-moveable` 0.10.0
* `moveable` 0.33.0
* `preact-moveable` 0.35.0
* `react-compat-moveable` 0.21.0
* `react-moveable` 0.36.0
* `svelte-moveable` 0.25.0
* `vue-moveable` 2.0.0-beta.27
* `vue3-moveable` 0.8.0
* `ngx-moveable` 0.30.0


moveable's new version is released.


Added object types to verticalGuidelines and horizontalGuidelines.

https://daybrush.com/moveable/storybook2/?path=/story/advanced-snappable--guidelines-with-custom-styles


```js

verticalGuidelines: [
   0,
   100,
   { pos: 200, className: "red" },
],

**Comment by alexconstantin** [comment]
@daybrush Thank you so much! This already is offering a lot of customisation options. One more follow-up question:

Is there a way to identify / retrieve these generated divs (in case of gaps, for example)?

![Screenshot 2022-07-26 at 10 07 58](https://user-images.githubusercontent.com/6921332/180945122-40695995-2dbb-438f-b179-afb7b97d4ba5.png)

Background: Starting from this issue https://github.com/daybrush/moveable/issues/200 , when working with a lot of html objects in the page, it can get crowded to display all snap distances to all elements at the same time, especially when a lot of distances are "compatible", so I am looking for a "display snap digits to the closest elements" / "display snaps only with a certain distance" solution (for example I have 4 snaps, 2 of them are 30px difference, the other 2 are 85px difference, so I will try to only display the 30px ones, based on some object distance calculations / number of concurrent snap digits being displayed.

Would something like this be achievable?

**Comment by daybrush** [comment]
@alexconstantin 

It's a good feature. I'll consider Maybe we'll add it in the next release.

**Comment by daybrush** [comment]
@alexconstantin 

* `lit-moveable` 0.11.2
* `moveable` 0.34.2
* `preact-moveable` 0.36.2
* `react-compat-moveable` 0.22.2
* `react-moveable` 0.37.2
* `svelte-moveable` 0.26.2
* `vue-moveable` 2.0.0-beta.30
* `vue3-moveable` 0.9.2
* `ngx-moveable` 0.31.2

moveable's new version is released.

Use `maxSnapElementGuidelineDistance` prop to adjust distance with element guidelines.


className is also applied to gaps.
```css
/* pos guidelines */
.moveable-normal.red {
    background: red!important;
}
/* gap guidelines */
.moveable-gap.red {
    background: red!important;
}
/* When snapped to an element in elementGuidelines */
.moveable-bold.red {
    background: red!important;
}
/* A dashed line between target and element */
.moveable-dashed.red {
    border-top-color: red!important;
    border-left-color: red!important;
}
```
