### ISSUE TITLE
Optionaly hide lines for elements inside group

### ISSUE THREAD

**Issue by Raserad** [daybrush/moveable#794]
@daybrush . Can we optionaly hide lines for elements inside group
In exaple
{
   target: ['.element1', ['.element2', '.element3'], '.element4'],
   hideGroupChildDefaultLines: true,
}

And hide lines for .element2 and .element3

**Comment by daybrush** [comment]
@Raserad 

not yet provided.

Could you try the CSS below?
```css
[data-line-key^="group-rect"] {
    display: none;
}
```
