### ISSUE TITLE
How can I customize the line thickness of the guidelines? 

### ISSUE THREAD

**Issue by syqhtt** [daybrush/moveable#922]
## Environments
* Framework name: Native HTML
* Framework version: Without version number
* Moveable Component version: 0.47.7
* Testable Address(optional): https://codepen.io/syqhtt/pen/YzJOojr

## Description
First of all, thank you for providing such an excellent plugin. 
But, I have a question. When I enable the display of guidelines, the default line thickness of the guidelines is 2px. 
How can I customize the line thickness of the guidelines? 
I didn't find the corresponding configuration in the API documentation.
![image](https://github.com/daybrush/moveable/assets/35021383/554eedc3-8bd8-4349-840c-14c4428efe8c)
I hope you can help me. Thank you very much!!!

**Comment by daybrush** [comment]
@syqhtt 

There is no guide yet.

 But, you can set the css as below.

```css
.moveable-bold.moveable-horizontal {
    height: 10px!important;
}
.moveable-dashed.moveable-horizontal.red {
  border-top-width: 10px!important;
}

```
