### ISSUE TITLE
How can i change the rotable icon?

### ISSUE THREAD

**Issue by AkashTvu** [daybrush/moveable#938]
## Environments
* Framework name: vue js
* Framework version: vue 2
* Moveable Component version: 2.beta.xx

## Description
I want to chane the rotation icon.

**Comment by daybrush** [comment]
@AkashTvu 

sorry. You can't change the DOM yet, but you can change the CSS.

Try using background or `:before` or `:after`.


<img width="263" alt="image" src="https://github.com/daybrush/moveable/assets/3433062/c636d17a-2358-4d8a-97c6-20c388042b81">


```css
.moveable-control-box .moveable-rotation .moveable-rotation-control {
        border-radius: 0;
        background: #f55;
        border: 0;
    }
```
